workflows:
  my_workflow:
    name: My Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Clean Flutter cache and install dependencies
        script:
          - flutter clean
          - flutter pub get
      # Add more scripts or steps as needed
